language: rust

env:
  global:
    - PROJECT_NAME=pandoc-emoji
    - RUST_BACKTRACE: full

matrix:
  include:
    - os: linux
      rust: nightly
      env: TARGET=i686-unknown-linux-musl
    - os: linux
      rust: nightly
      env: TARGET=x86_64-unknown-linux-musl
    - os: osx
      rust: nightly
      env: TARGET=x86_64-apple-darwin
deploy:
- provider: releases
  skip_cleanup: true
  api_key:
  secure: "wPHlsfatoTv6VP6MoJ2CC6ew/9kEmPpzSXg9YV8loRUPj5XGclRgyUEBnJnrx0IrU/SQqWCSnFzzg0161V1hu9EJBmuqnXOYTUWnldSAbmo71Bck8Y0oskHpTtXpkJ+wQHhuxLsBNpRRQ5tjPd73DfAHz4oqW8J2KLuL6Mg9BjrcovnMe5+ktv89pGee0hObDJBSzaR1CGQ/UptlOdm3dFUQcZbQJmQeEECJ/vx5+qlrCRG/TY/pL9sGFnmvxclMSWTCtqjpSWs2kRfKwsMwscCraLdMyZ8b2HJc2+HDeH+9l3WtzKsgjo2Ft2IPXzxg16ylfGg23QbnIzLtKlGDAdSHkMl0BLPqcwItt6w7GkFrPVfz+0DDH7aWsTjNkXGTMRr+E4m6SIGHmQRCgNp3k0KnfLSqFzsBSCVNg/j5E/GB09x5IS78/NeFVaJc9IDGjREHgO0WIhLVzmG3rHpX4nXzYAcV3rS8Gp0SAZNDNj60e+7uFDv+gmsJnx3tQSZa1A+r1X+XD7KlfqG28CVoF0rOouVPwFFrxgu85QCNoWReDhWNyg8lpDse79zaTmeVEmlvehPrWLXk9K5Xkrc73aCKMaJaphMsNv0IZ1gG02FJOI4Q0WENHR6v4P+SCW+zVVFLQHLv8dPggbUpiwExO+btFxQxO7U78fBl8deBgVo="
  file: pandoc-emoji-$TRAVIS_TAG.zip
  on:
    tags: true
